name: fsuper_example
description: Demonstrates how to use the fsuper plugin.
publish_to: none

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  cupertino_icons: ^0.1.2
  fbutton: ^1.0.4
  fcommon:
    git:
      ref: master
      url: git@github.com:Fliggy-Mobile/fcommon.git
  fdottedline: ^1.0.0
  ffloat: ^1.0.1
  flutter:
    sdk: flutter
  fradio: ^1.0.1
  frefresh: ^1.1.0
  fsearch: ^1.0.0
  fswitch: ^1.1.2

dependency_overrides:
  fcontrol: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fsuper:
    path: ../

flutter:
  assets:
  - assets/
  uses-material-design: true
